name: "Python Dependency Installation"
description: "Install Python dependencies from requirements.txt file"
inputs:
  path: # id
    description: "Path to requirements.txt file"
    required: false
    default: "requirements.txt"
  update-pip: # id
    description: "Boolean for pip upgrade prior to the dependency installation (default='true')"
    required: false
    default: "true" # options "true", "false"
  update-setuptools:
    description: "Boolean for setuptools install/upgrade prior to the dependency installation (default='true')"
    required: false
    default: "true" # options "true", "false"
  update-wheel:
    description: "Boolean for wheel install/upgrade prior to the dependency installation (default='true')"
    required: false
    default: "true" # options "true", "false"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "terminal"
  color: "blue"
