name: macOS CI

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  pull_request:

jobs:
  ci-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: macOS CI
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python environment report
        run: python -c "import sys; print(sys.version)"
      - name: Run ${{ matrix.python-version }} platform tests (default)
        uses: py-actions/py-dependency-install@642387473628e92c4b9ac198b5ba51b9102d3f08
        with:
          requirements-path: "tests/requirements.txt"
      - name: Run ${{ matrix.python-version }} platform tests (with args)
        uses: py-actions/py-dependency-install@642387473628e92c4b9ac198b5ba51b9102d3f08
        with:
          requirements-path: "tests/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
